### ISSUE TITLE
SceneLayer queries are not available without companion feature layer

### ISSUE THREAD

**Issue by simongis** [ArcGIS/c-through#5]
If I create a scene package from Pro and upload to an ArcGIS Online account, tweak the settings in your app, the side panel fails to load with the following reported in the browser console:

_"SceneLayer queries are not available without companion feature layer"_

I assume there is not an easy workaround to getting this to work via ArcGIS Online using scene packages?

I also tried publishing a multipatch scene to ArcGIS Enterprise, but ran into problems (post on [GeoNet](https://community.esri.com/message/719319-failed-to-publish-web-layer))

**Comment by gutierrezj** [comment]
@simongis thanks for your question. You will definitely need the Feature Layer for queries, so publishing the SLPK alone will not be enough.

The 2 recommended workflows are:
a) in ArcGIS Online: publish a multipatch FileGDB as a Feature Service, then generate a Scene Layer from the Feature Service.
b) in ArcGIS Enterprise: publish your Scene Layer from ArcGIS Pro directly, this will create the multipatch Feature Layer and the Scene Layer automatically.

**Comment by simongis** [comment]
Thanks @gutierrezj 
Any chance you could elaborate on the steps for option a)

I had  a building layer (feature class) that I ran the 'Layer 3D to Feature Class' tool on (in Pro) to create my multipatch layer.

Are you saying publish the original feature class from Pro instead of the multipatch?
If I try and right click this layer (which  I have extruded using  building  height) from the scene and share web layer I get a warning as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/2769383/31117077-2fc9d724-a874-11e7-9e16-76ba9d0aab14.png)

**Comment by gutierrezj** [comment]
Take a look at this blog, the section on "Publishing Hosted 3D Object Scene Layers", about how to do it from Pro: https://blogs.esri.com/esri/arcgis/2017/09/25/authoring-3d-layers-and-creating-web-scenes-in-arcgis-online/

Alternatively you can Zip your FGDB with your multipatch Feature Class and if the ZIP file is smaller than 1GB you can upload it directly to your ArcGIS Online Content. This is also explained in this blog: https://blogs.esri.com/esri/arcgis/2017/01/03/72321/

**Comment by simongis** [comment]
Perfect, that blog helped a lot

http://simonjackson.s3.amazonaws.com/PublicFacing/geoscape/index.html?demo

Any idea why the page is loading up with the bottom right slider below the scene and off-screen?

![image](https://user-images.githubusercontent.com/2769383/31122501-dfdca264-a887-11e7-937e-52d252faa4ce.png)

**Comment by simongis** [comment]
Ill raise a new issue, thanks!
