### ISSUE TITLE
"l" forgotten in "value" in applyRenderer.js line 187

### ISSUE THREAD

**Issue by ArthurGenet** [ArcGIS/c-through#8]
hello, thank you for the nice code, I just wanted to tell you that there is a little mistake that creates a wrong visualization when you click on the histogram for area.
Have a nice day :)

**Comment by lisastaehli** [comment]
Hi @ArthurGenet & thanks for pointing this out :) what a silly mistake. It's fixed now https://github.com/Esri/c-through/commit/52d2aad4b0f5a82d8b611d9b712898a26d148db7.

Have a nice day! :)
